# Generated by Django 5.2.17 on 2026-08-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion_ip', models.GenericIPAddressField(unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('segmento_ip', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'redes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoCritico',
            fields=[
            ],
            options={
                'verbose_name': 'dispositivo crítico',
                'verbose_name_plural': 'dispositivos críticos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dispositivos.dispositivo',),
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latencia_ms', models.FloatField(blank=True, null=True)),
                ('errores', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='dispositivos.dispositivo')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='dispositivos.red'),
        ),
    ]
